[project]
name = "hospital-neo4j-etl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black>=25.1.0",
    "neo4j>=5.28.1",
    "python-dotenv>=1.1.1",
    "retry>=0.9.2",
]
